-- ==============================================================================
-- OMS (Operation Management System) - Complete Supabase Database Schema
-- Version: v1.22
-- Includes: Tables, Constraints, Indexes, Row Level Security (RLS) & Storage
-- ==============================================================================

-- 1. Enable pgcrypto for UUID generation if needed
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==============================================================================
-- TABLE 1: system_settings (ข้อมูลบริษัทและการตั้งค่าระบบ)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.system_settings (
    id TEXT PRIMARY KEY DEFAULT 'default',
    company_name TEXT NOT NULL DEFAULT 'บริษัท โอเอ็มเอส โซลูชั่น จำกัด',
    company_address TEXT DEFAULT '123/45 หมู่ 1 ถ.สุขุมวิท ต.คลองเตย อ.คลองเตย จ.กรุงเทพมหานคร 10110',
    tax_id TEXT DEFAULT '0105555555555',
    banks JSONB DEFAULT '[{"bank": "กสิกรไทย", "branch": "สุขุมวิท", "account_name": "บจก. โอเอ็มเอส", "account_no": "0123456789"}]'::jsonb,
    security_settings JSONB DEFAULT '{"maxFailedBeforeDelay": 5, "delaySeconds": 30, "maxFailedBeforeLock": 10}'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW())
);

-- ==============================================================================
-- TABLE 2: warehouses (คลังสินค้า)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.warehouses (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    address JSONB DEFAULT '{}'::jsonb,
    contact TEXT,
    phone TEXT,
    type TEXT DEFAULT 'sub', -- 'main', 'sub', 'sales'
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW())
);

-- ==============================================================================
-- TABLE 3: users (ผู้ใช้งานระบบ)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT DEFAULT '123',
    fullname TEXT NOT NULL,
    nickname TEXT,
    phone TEXT,
    email TEXT,
    role TEXT NOT NULL DEFAULT 'sales', -- admin, purchasing, warehouse, sales, accounting, management
    area TEXT DEFAULT 'HQ',
    warehouse_id TEXT REFERENCES public.warehouses(id) ON DELETE SET NULL,
    shipping_address TEXT DEFAULT '-',
    failed_attempts INTEGER DEFAULT 0,
    locked_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW())
);

-- ==============================================================================
-- TABLE 4: vendors (ผู้จัดจำหน่าย / ซัพพลายเออร์)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.vendors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    contact TEXT,
    phone TEXT,
    email TEXT,
    tax_id TEXT,
    address JSONB DEFAULT '{}'::jsonb,
    products JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW())
);

-- ==============================================================================
-- TABLE 5: customers (ลูกค้า / ร้านค้า)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE,
    name TEXT NOT NULL,
    contact TEXT,
    phone TEXT,
    line_id TEXT,
    address JSONB DEFAULT '{}'::jsonb,
    shipping_differs BOOLEAN DEFAULT FALSE,
    shipping_address JSONB DEFAULT NULL,
    vat_req BOOLEAN DEFAULT FALSE,
    tax_name TEXT,
    tax_id TEXT,
    tax_address TEXT,
    assigned_sales JSONB DEFAULT '[]'::jsonb, -- e.g. ["sales", "admin"]
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW())
);

-- ==============================================================================
-- TABLE 6: products (สินค้าและสต็อกคงเหลือ)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku TEXT NOT NULL,
    name TEXT NOT NULL,
    category TEXT DEFAULT 'ทั่วไป',
    cost_price NUMERIC(12,2) DEFAULT 0,
    wholesale_price NUMERIC(12,2) DEFAULT 0,
    stock_qty INTEGER DEFAULT 0,
    pending_in INTEGER DEFAULT 0,
    location TEXT DEFAULT '-',
    warehouse TEXT REFERENCES public.warehouses(id) ON DELETE CASCADE,
    unit TEXT DEFAULT 'กล่อง',
    carton_qty INTEGER DEFAULT 1,
    image_url TEXT, -- รูปภาพสินค้าที่เก็บใน Supabase Storage
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW())
);

-- ==============================================================================
-- TABLE 7: purchase_orders (ใบสั่งซื้อ PO)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.purchase_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_no TEXT UNIQUE NOT NULL,
    vendor_id BIGINT REFERENCES public.vendors(id) ON DELETE SET NULL,
    vendor_name TEXT NOT NULL,
    status TEXT DEFAULT 'Pending', -- Pending, Completed, Cancelled
    payment_status TEXT DEFAULT 'Unpaid', -- Unpaid, Partial Paid, Paid, Overpaid
    total_amount NUMERIC(12,2) DEFAULT 0,
    unpaid_amount NUMERIC(12,2) DEFAULT 0,
    created_by TEXT,
    date DATE DEFAULT CURRENT_DATE,
    completed_date DATE,
    items JSONB DEFAULT '[]'::jsonb,
    notes TEXT,
    attachment_url TEXT, -- ไฟล์แนบใบสั่งซื้อใน Supabase Storage
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW())
);

-- ==============================================================================
-- TABLE 8: goods_receipts (ประวัติการรับสินค้าเข้าคลัง)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.goods_receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_no TEXT NOT NULL,
    vendor_name TEXT,
    date DATE DEFAULT CURRENT_DATE,
    received_by TEXT,
    items JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW())
);

-- ==============================================================================
-- TABLE 9: purchase_payments (การจ่ายเงินค่าสินค้าจัดซื้อ)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.purchase_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_id BIGINT REFERENCES public.purchase_orders(id) ON DELETE SET NULL,
    po_no TEXT,
    vendor_name TEXT,
    date DATE DEFAULT CURRENT_DATE,
    amount NUMERIC(12,2) DEFAULT 0,
    net_amount NUMERIC(12,2) DEFAULT 0,
    unpaid_amount NUMERIC(12,2) DEFAULT 0,
    method TEXT DEFAULT 'โอนเงิน',
    status TEXT DEFAULT 'Completed',
    sales_ref TEXT,
    customer_ref TEXT,
    sales_name TEXT,
    created_by TEXT,
    slip_url TEXT, -- สลิปโอนเงินจ่ายซัพพลายเออร์ ใน Supabase Storage
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW())
);

-- ==============================================================================
-- TABLE 10: sales_orders (รายการสั่งขาย SO)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.sales_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    so_no TEXT UNIQUE NOT NULL,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE SET NULL,
    customer_name TEXT NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    subtotal NUMERIC(12,2) DEFAULT 0,
    vat_amount NUMERIC(12,2) DEFAULT 0,
    total_amount NUMERIC(12,2) DEFAULT 0,
    vat_req BOOLEAN DEFAULT FALSE,
    delivery_type TEXT DEFAULT 'จัดส่งโดยคลัง',
    payment_type TEXT DEFAULT 'เครดิต',
    payment_date DATE,
    status TEXT DEFAULT 'Pending', -- Pending, Approved, ไม่อนุมัติ, Completed, Cancelled
    payment_status TEXT DEFAULT 'Unpaid', -- Unpaid, Pending Review, Paid
    sales_person TEXT,
    po_no TEXT,
    items JSONB DEFAULT '[]'::jsonb,
    delivery_address JSONB DEFAULT NULL,
    tax_invoice_issued BOOLEAN DEFAULT FALSE,
    tax_invoice_no TEXT,
    tax_invoice_date DATE,
    tax_invoice_img TEXT, -- รูปภาพใบกำกับภาษี ใน Supabase Storage
    slip_url TEXT,        -- รูปภาพสลิปโอนเงินชำระค่าสินค้า ใน Supabase Storage
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW())
);

-- ==============================================================================
-- TABLE 11: sales_receipts (การรับชำระเงิน/สลิปโอนเงินจากลูกค้า)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.sales_receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref_no TEXT,
    so_no TEXT,
    customer_name TEXT,
    amount NUMERIC(12,2) DEFAULT 0,
    date DATE DEFAULT CURRENT_DATE,
    method TEXT DEFAULT 'โอนเงิน',
    status TEXT DEFAULT 'Pending', -- Pending, Approved
    sales_person TEXT,
    slip_url TEXT, -- สลิปโอนเงินลูกค้า ที่ผ่านการบีบอัด Client-Side และอัปโหลดขึ้น Supabase Storage
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW())
);

-- ==============================================================================
-- TABLE 12: requisitions (ใบขอเบิกสินค้า)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.requisitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    req_no TEXT UNIQUE NOT NULL,
    so_id BIGINT REFERENCES public.sales_orders(id) ON DELETE SET NULL,
    so_no TEXT,
    type TEXT DEFAULT 'เบิกเพื่อสต็อก', -- 'เบิกเพื่อสต็อก', 'เบิกเพื่อขาย'
    status TEXT DEFAULT 'Pending',     -- 'Pending', 'Approved', 'Completed'
    req_by TEXT,
    date DATE DEFAULT CURRENT_DATE,
    to_wh TEXT,
    req_method TEXT DEFAULT 'จัดส่งตามที่อยู่',
    delivery_address TEXT,
    items JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW())
);

-- ==============================================================================
-- TABLE 13: shipments (ประวัติการจัดส่งสินค้าและเลขพัสดุ)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.shipments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    req_id BIGINT REFERENCES public.requisitions(id) ON DELETE SET NULL,
    req_no TEXT,
    type TEXT,
    to_wh TEXT,
    receiver TEXT,
    sales TEXT,
    address TEXT,
    date DATE DEFAULT CURRENT_DATE,
    carrier TEXT,
    tracking TEXT,
    doc TEXT,
    items JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW())
);

-- ==============================================================================
-- TABLE 14: login_history (ประวัติการเข้าสู่ระบบ)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.login_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user" TEXT,
    fullname TEXT,
    time TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()),
    ip TEXT DEFAULT '127.0.0.1',
    status TEXT
);

-- ==============================================================================
-- INDEXES สำหรับความเร็วในการค้นหา
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_products_sku ON public.products(sku);
CREATE INDEX IF NOT EXISTS idx_products_warehouse ON public.products(warehouse);
CREATE INDEX IF NOT EXISTS idx_sales_orders_so_no ON public.sales_orders(so_no);
CREATE INDEX IF NOT EXISTS idx_sales_orders_status ON public.sales_orders(status);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_po_no ON public.purchase_orders(po_no);
CREATE INDEX IF NOT EXISTS idx_requisitions_req_no ON public.requisitions(req_no);
CREATE INDEX IF NOT EXISTS idx_requisitions_so_id ON public.requisitions(so_id);
CREATE INDEX IF NOT EXISTS idx_shipments_tracking ON public.shipments(tracking);

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- อนุญาตให้อ่านและเขียนข้อมูลได้ตาม API Key (Anon / Authenticated)
-- ==============================================================================
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.warehouses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.goods_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.requisitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shipments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.login_history ENABLE ROW LEVEL SECURITY;

-- สร้างนโยบายอ่าน/เขียนสาธารณะสำหรับแอปรองรับ Anon Key
DO $$
DECLARE
    tbl text;
    tables text[] := ARRAY[
        'system_settings', 'warehouses', 'users', 'vendors', 'customers',
        'products', 'purchase_orders', 'goods_receipts', 'purchase_payments',
        'sales_orders', 'sales_receipts', 'requisitions', 'shipments', 'login_history'
    ];
BEGIN
    FOREACH tbl IN ARRAY tables LOOP
        EXECUTE format('DROP POLICY IF EXISTS "Public read access on %I" ON public.%I', tbl, tbl);
        EXECUTE format('CREATE POLICY "Public read access on %I" ON public.%I FOR SELECT USING (true)', tbl, tbl);
        
        EXECUTE format('DROP POLICY IF EXISTS "Public insert access on %I" ON public.%I', tbl, tbl);
        EXECUTE format('CREATE POLICY "Public insert access on %I" ON public.%I FOR INSERT WITH CHECK (true)', tbl, tbl);
        
        EXECUTE format('DROP POLICY IF EXISTS "Public update access on %I" ON public.%I', tbl, tbl);
        EXECUTE format('CREATE POLICY "Public update access on %I" ON public.%I FOR UPDATE USING (true) WITH CHECK (true)', tbl, tbl);
        
        EXECUTE format('DROP POLICY IF EXISTS "Public delete access on %I" ON public.%I', tbl, tbl);
        EXECUTE format('CREATE POLICY "Public delete access on %I" ON public.%I FOR DELETE USING (true)', tbl, tbl);
    END LOOP;
END $$;

-- ==============================================================================
-- GRANT PERMISSIONS TO ANON AND AUTHENTICATED ROLES
-- แก้ปัญหา "permission denied for table ..." สำหรับ Supabase REST API
-- ==============================================================================
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO anon, authenticated, service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON ROUTINES TO anon, authenticated, service_role;

-- ==============================================================================
-- SUPABASE STORAGE BUCKET: oms-storage
-- สำหรับเก็บสลิปการโอนเงิน (slips/), ใบกำกับภาษี (invoices/), รูปสินค้า (products/)
-- ==============================================================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('oms-storage', 'oms-storage', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- นโยบาย Storage ให้ทุกคนสามารถดูรูปได้ (Public Read)
DROP POLICY IF EXISTS "Public Storage Read" ON storage.objects;
CREATE POLICY "Public Storage Read" ON storage.objects
FOR SELECT USING (bucket_id = 'oms-storage');

-- นโยบาย Storage ให้อัปโหลดไฟล์รูปภาพได้
DROP POLICY IF EXISTS "Public Storage Insert" ON storage.objects;
CREATE POLICY "Public Storage Insert" ON storage.objects
FOR INSERT WITH CHECK (bucket_id = 'oms-storage');

-- นโยบาย Storage ให้อัปเดตหรือลบไฟล์ได้
DROP POLICY IF EXISTS "Public Storage Update" ON storage.objects;
CREATE POLICY "Public Storage Update" ON storage.objects
FOR UPDATE USING (bucket_id = 'oms-storage');

DROP POLICY IF EXISTS "Public Storage Delete" ON storage.objects;
CREATE POLICY "Public Storage Delete" ON storage.objects
FOR DELETE USING (bucket_id = 'oms-storage');
